{{- if .Values.scripts.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "networktools.fullname" . }}-scripts
  labels:
    {{- include "networktools.labels" . | nindent 4 }}
data:
  {{- range $name, $content := .Values.scripts.data }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
